# Generated by Django 5.0.6 on 2024-06-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fId', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectCode', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(default='NA', max_length=10)),
                ('parent', models.CharField(default='NA', max_length=30)),
                ('address', models.CharField(default='NA', max_length=50)),
                ('subjectCode', models.CharField(default='NA', max_length=20)),
                ('assignment1', models.IntegerField(default=0)),
                ('assignment2', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
