# Generated by Django 5.0.6 on 2024-06-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student', 'subjectCode'), name='unique_student_subject'),
        ),
    ]
