# Generated by Django 5.0.6 on 2024-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Credit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='classtest1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='classtest2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='endTerm',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='midTerm',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
