# Generated by Django 5.0.6 on 2024-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_faculty_credit_remove_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='rollNo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
