# Generated by Django 5.0.6 on 2024-06-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_unique_student_subject'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_student_subject',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_no', 'subjectCode')},
        ),
    ]
