# Generated by Django 5.0.6 on 2024-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_subject_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='assignment1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assignment2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
